site_name: 数理化wiki
site_url: http://43.139.175.183:5566/
nav:
  - 主页: index.md
  - 数学:
    - 小学奥数: 
      - 主页: 数学/小学奥数/main.md
    - 初中课内:
      - 主页: 数学/初中课内/main.md
    - 初中竞赛:
      - 主页: 数学/初中竞赛/main.md
  # - 物理:
  #   - 初中课内:
  #   - 初中竞赛:
  # - 化学:
  #   - 初中课内:
  #   - 初中竞赛:
  - 关于: about.md
theme:
  name: material